/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import control.ClienteConexion;
import entidades.Cliente;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import okhttp3.FormBody;
import okhttp3.RequestBody;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Christian
 */
public class ListaClientes extends javax.swing.JPanel {

    ClienteConexion cliente = new ClienteConexion();
    JSONArray clientes;
    static String seleccion;
    static Color bkColor;

    public ListaClientes() {
        initComponents();
        this.bkColor = new Color(255, 204, 255);
        fillData();
        seleccionInicial();
    }

    private void fillData() {
        JSONObject data = cliente.getJSON("https://proyectosuta.000webhostapp.com/gcs_proyecto/client/getAllClients.php");
        clientes = (JSONArray) data.get("clientes");
        for (int i = 0; i < clientes.length(); i++) {
            Cliente cliente = new Cliente();
            JSONObject estudianteJson = (JSONObject) this.clientes.get(i);
            cliente.setCedula(estudianteJson.getString("numero_documento"));
            cliente.setNombre(estudianteJson.getString("primer_nombre"));
            cliente.setNombre1(estudianteJson.getString("segundo_nombre"));
            cliente.setApellido(estudianteJson.getString("apellido_paterno"));
            cliente.setApellido1(estudianteJson.getString("apellido_materno"));
            cliente.setTelefono(estudianteJson.getString("telefono"));
            cliente.setDireccion(estudianteJson.getString("direccion"));
            crearFicha(cliente, i);
        }
    }

    private void seleccionInicial() {
        for (int i = 0; i < jpnlClientes.getComponentCount(); i++) {
            if (i == 0) {
                ((FichaCliente) jpnlClientes.getComponent(i)).getBkFicha().setBackground(bkColor);
                seleccion = ((FichaCliente) jpnlClientes.getComponent(i)).getEstudiante().getCedula();
            } else {
                ((FichaCliente) jpnlClientes.getComponent(i)).getBkFicha().setBackground(Color.white);
            }
        }
    }

    private void crearFicha(Cliente cliente, int position) {
        FichaCliente ficha = new FichaCliente(cliente);
        jpnlClientes.add(ficha).setBounds(0, 112 * position, 605, 112);
        jpnlClientes.setPreferredSize(new Dimension(605, 112 * position));
    }

    private void editarCliente() {
        Cliente cliente = new Cliente();
        for (int i = 0; i < jpnlClientes.getComponentCount(); i++) {
            if (((FichaCliente) jpnlClientes.getComponent(i)).getBkFicha().getBackground().getRGB() == -13057) {
                cliente = ((FichaCliente) jpnlClientes.getComponent(i)).getEstudiante();
                break;
            }
        }
        new CambiaPanel(this, new EditarCliente(cliente));
    }

    public static void seleccionarRegistro(String id) {
        for (int i = 0; i < jpnlClientes.getComponentCount(); i++) {
            if (((FichaCliente) jpnlClientes.getComponent(i)).getEstudiante().getCedula().equals(id)) {
                ((FichaCliente) jpnlClientes.getComponent(i)).getBkFicha().setBackground(bkColor);
                seleccion = ((FichaCliente) jpnlClientes.getComponent(i)).getEstudiante().getCedula();
            } else {
                ((FichaCliente) jpnlClientes.getComponent(i)).getBkFicha().setBackground(Color.white);
            }
        }
    }

    private void confirmarEliminar() {
        if (JOptionPane.showConfirmDialog(new JInternalFrame(), "¿Estás seguro?", "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            eliminarEstudiante(seleccion);
            new CambiaPanel(this, new ListaClientes());
            this.seleccionInicial();
        }
    }
    
    private void eliminarEstudiante(String id) {
        ClienteConexion cliente = new ClienteConexion();
        RequestBody requestBody = new FormBody.Builder().add("numero_documento", id).build();
        JSONObject response = cliente.postJSON("https://proyectosuta.000webhostapp.com/gcs_proyecto/client/deleteClient.php", requestBody);
        boolean verificar = response.getBoolean("ok");
        if (verificar) {
            JOptionPane.showMessageDialog(this, "Se eliminó correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "No se eliminó el cliente");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPerfil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtBienvenida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpnlClientes = new javax.swing.JPanel();
        jpnlEliminar = new javax.swing.JPanel();
        jtxtEliminar = new javax.swing.JLabel();
        jlblBotonEliminar = new javax.swing.JLabel();
        jpnlEditar = new javax.swing.JPanel();
        jtxtEditar = new javax.swing.JLabel();
        jlblBotonEditar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(415, 390));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlPerfil.setBackground(new java.awt.Color(28, 59, 112));
        jpnlPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEMA DE FACTURACIÓN");
        jpnlPerfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 22, 300, 30));

        jtxtBienvenida.setFont(new java.awt.Font("Poppins SemiBold", 0, 32)); // NOI18N
        jtxtBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        jtxtBienvenida.setText("Clientes");
        jpnlPerfil.add(jtxtBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 67, 579, 40));

        add(jpnlPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 623, 130));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jpnlClientes.setPreferredSize(new java.awt.Dimension(621, 585));

        javax.swing.GroupLayout jpnlClientesLayout = new javax.swing.GroupLayout(jpnlClientes);
        jpnlClientes.setLayout(jpnlClientesLayout);
        jpnlClientesLayout.setHorizontalGroup(
            jpnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        jpnlClientesLayout.setVerticalGroup(
            jpnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jpnlClientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 623, 390));

        jpnlEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jpnlEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtEliminar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jtxtEliminar.setForeground(new java.awt.Color(28, 59, 112));
        jtxtEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtxtEliminar.setText("ELIMINAR");
        jtxtEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtxtEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtEliminarMouseClicked(evt);
            }
        });
        jpnlEliminar.add(jtxtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 180, 45));

        jlblBotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buttonB_180_45.png"))); // NOI18N
        jpnlEliminar.add(jlblBotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 45));

        add(jpnlEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 180, 45));

        jpnlEditar.setBackground(new java.awt.Color(255, 255, 255));
        jpnlEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtEditar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jtxtEditar.setForeground(new java.awt.Color(255, 255, 255));
        jtxtEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtxtEditar.setText("EDITAR");
        jtxtEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtxtEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtEditarMouseClicked(evt);
            }
        });
        jpnlEditar.add(jtxtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 45));

        jlblBotonEditar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jlblBotonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jlblBotonEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblBotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_180_45.png"))); // NOI18N
        jlblBotonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpnlEditar.add(jlblBotonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 45));

        add(jpnlEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 530, 180, 45));
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEliminarMouseClicked
        confirmarEliminar();
    }//GEN-LAST:event_jtxtEliminarMouseClicked

    private void jtxtEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarMouseClicked
        editarCliente();
    }//GEN-LAST:event_jtxtEditarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblBotonEditar;
    private javax.swing.JLabel jlblBotonEliminar;
    private static javax.swing.JPanel jpnlClientes;
    private javax.swing.JPanel jpnlEditar;
    private javax.swing.JPanel jpnlEliminar;
    private javax.swing.JPanel jpnlPerfil;
    private javax.swing.JLabel jtxtBienvenida;
    private javax.swing.JLabel jtxtEditar;
    private javax.swing.JLabel jtxtEliminar;
    // End of variables declaration//GEN-END:variables
}
